### ISSUE TITLE
DLC Builder for Linux v0.9.x Freeze with XFCE4

### ISSUE THREAD

**Issue by erockce** [iminashi/Rocksmith2014.NET#12]
When I open the program, it binds to the upper corner, Whisker Menu is no longer available, the desktop becomes an "image" where I cannot get back to it, and I cannot switch to another program.

Also I can drag the program around and it creates multiple "after images" all over the screen.

The only way to fix is exit the program, use the "Ctrl-Esc" hot key that brought back the desktop but no panels.  Then I could right-click to access XFCE's application menu to log out.

I'm using EndeavourOS Atlantis (an ArchLinux-based distro) with latest Xorg, and display drivers for Intel.

I use a dark GTK2 based icon and theme set which the program seems to comply with.

I just started playing around with v0.7.5 that I acquired in October last year.  It was only recently I wanted to try the program.  When I started it prompted me to download an update.

I could downgrade and go backwards till I find the most recent version that doesn't have this issue....

Pictures describe better so I am attaching an example of what's happening:

 ![DLCBuilder-linux-0 9 1-freeze-Screenshot_2022-02-12_16-30-15](https://user-images.githubusercontent.com/17682973/153732269-4fde7ec8-d856-4a4d-9ac2-477a0f1ea463.png)

Please let me know if you'd like some more information about my setup.

**Comment by iminashi** [comment]
Thanks for reporting the issue. If 0.7.5 worked correctly, it might be caused by updating the version of Avalonia used.

I've released 0.9.2 just now, which updates the version of Avalonia to 0.10.12. It probably won't fix this issue, but it does fix some crashes on Linux.

On my laptop that has Pop OS/Gnome/Intel I have no issues running the program.

**Comment by erockce** [comment]
What a strange issue.

I have the same problem with 0.9.2 unfortunately.

![DLCBuilder-linux-0 9 2-freeze-Screenshot_2022-02-13_11-41-13](https://user-images.githubusercontent.com/17682973/153769772-22aaec81-847c-4493-b2a3-d0436bf63a97.png)

**Comment by iminashi** [comment]
The configuration files are stored in ~/.rs2-dlcbuilder. I don't  see how they could cause such a problem though.

About specific requirements, I can't really say, since I'm not a Linux expert.
[https://github.com/AvaloniaUI/Avalonia/wiki/Runtime-Requirements](https://github.com/AvaloniaUI/Avalonia/wiki/Runtime-Requirements)

**Comment by erockce** [comment]
Hi @iminashi

I've come back and now re-tested with version 1.2.0.

At the moment I've switched to a tiling window manager (`bspwm`).

I do not experience the issue I originally reported.

So...I'm considering this issue closed.
